<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit09f5eceba4bc63da9aa706159cb01f11
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit09f5eceba4bc63da9aa706159cb01f11', 'loadClassLoader'), true, false);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit09f5eceba4bc63da9aa706159cb01f11', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit09f5eceba4bc63da9aa706159cb01f11::getInitializer($loader));

        $loader->register(false);

        return $loader;
    }
}
