name: Build
on: [push, pull_request]

jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/payline
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/payline

      - name: Install composer dependencies
        run: composer install --no-dev -o

      - name: Create & upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ github.event.repository.name }}-${{ github.base_ref }}
          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/payline

#  build-and-release-draft:
#    name: Build & Release draft 1
#    uses: PrestaShop/.github/.github/workflows/build-release.yml@master
