name: Build
on: [push, pull_request]

jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install composer dependencies
        run: composer install --no-dev -o
      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v2.0
      - name: Prepare auto-index tool
        run: composer global require prestashop/autoindex
      - name: Generate index.php
        run: ~/.composer/vendor/bin/autoindex
      - name: Move to rename
        run: cp -r /home/runner/work/${{ github.event.repository.name }} /home/runner/work/payline
      - name: Create & upload artifact
        working-directory: /home/runner/work/payline
        uses: actions/upload-artifact@v4.4.3
        with:
#          name: ${{ github.event.repository.name }}
          name: payline
          path: /home/runner/work/payline
#          path: /home/runner/work/${{ github.event.repository.name }}

#  build-and-release-draft:
#    name: Build & Release draft 1
#    uses: PrestaShop/.github/.github/workflows/build-release.yml@master
#  build:
#    name: Build dependencies & create artifact
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 7.4
#          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, ext-zip
#
#      - name: Install composer dependencies
#        run: composer install --ansi --prefer-dist --no-interaction --no-progress --no-dev
#
#      - name: Setup node
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20.x'
#
#      - name: Install and build npm dependencies
#        run: |
#          npm install --prefix ./_dev
#          npm run vite:build --prefix ./_dev
#
#      - name: Clean-up project
#        uses: PrestaShopCorp/github-action-clean-before-deploy@v2.0
#        with:
#          paths: storybook _dev
#
#      - name: Create & upload artifact
#        uses: actions/upload-artifact@v4.1.0
#        with:
#          name: ${{ github.event.repository.name }}
#          path: '.'
