name: Build
#on: [push, pull_request]
on:
  release:
    types: [published]

jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/payline
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/payline
#
#      - name: Install composer dependencies
#        run: composer install --no-dev -o
#
#      - name: Create & upload artifact
#        uses: actions/upload-artifact@v4.4.3
#        with:
#          name: ${{ github.event.repository.name }}-${{ github.ref_name }}
#          path: |
#            /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
#            !/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/payline/composer.*
