name: Build
on: [push, pull_request]

jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: /home/runner/work/payline
    steps:
      - name: create payline folder
        run: mkdir payline

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./payline

      - name: Install composer dependencies
        run: cd payline && composer install --no-dev -o

      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v2.0
        with:
          paths: ./payline

      - name: Prepare auto-index tool
        run: cd payline && composer global require prestashop/autoindex

      - name: Generate index.php
        run: ~/.composer/vendor/bin/autoindex

      - name: Create & upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ github.event.repository.name }}
#          name: payline
          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
#          path: /home/runner/work/payline
#          path: /home/runner/work/${{ github.event.repository.name }}

#  build-and-release-draft:
#    name: Build & Release draft 1
#    uses: PrestaShop/.github/.github/workflows/build-release.yml@master
