name: Build package
on:
  release:
    types: [published]

jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      VERSION: ${{ github.ref_name }}
      FOLDER_NAME: payline
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, ctype, json, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Archive
        run: composer archive --file=$REPO_NAME --format=zip

      - name: zip, zip, zipping
        run: rm -rf $FOLDER_NAME && unzip $REPO_NAME.zip -d $FOLDER_NAME && rm $REPO_NAME.zip && zip -r ${REPO_NAME}-${VERSION}.zip $FOLDER_NAME && rm -rf $FOLDER_NAME

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ZIP_FILE="${REPO_NAME}-${VERSION}.zip"
          gh release upload ${{ github.event.release.tag_name }} ${ZIP_FILE} --clobber
